### ISSUE TITLE
Switch off NodeSource

### ISSUE THREAD

**Issue by niftylettuce** [Oefenweb/ansible-nodejs#19]
I think we should switch off NodeSource, the main reason being that pinning to a specific version is not possible.

Instead, we could use [nvm](https://github.com/nvm-sh/nvm) (preferred) or [n](https://github.com/tj/n).

Ref: https://github.com/leonidas/ansible-nvm

**Comment by tersmitten** [comment]
For us this is not really an issue

**Comment by tersmitten** [comment]
But thanks for the information
