### ISSUE TITLE
Install exact version is not possible

### ISSUE THREAD

**Issue by attenzione** [Oefenweb/ansible-nodejs#20]
Can't install the exact version, however it's mentioned in README.

**Comment by tersmitten** [comment]
Apparently that was added in https://github.com/Oefenweb/ansible-nodejs/commit/97d46020224617b7b6fe31fbf77ad020b090255f#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5, but it's not true.

**Comment by attenzione** [comment]
Yes, I saw this commit. But then `nodejs_version_map` isn't working.

**Comment by tersmitten** [comment]
Yes, so the comment should be removed

**Comment by tersmitten** [comment]
See #19

**Comment by tersmitten** [comment]
Cleaned it up in #25
